// Words that trigger a little celebration toast when they land on the board
// (via the top move or the player's own move).
export const EASTER_EGGS: Record<string, { emoji: string; text: string }> = {
  SALUT:     { emoji: '👋', text: 'Salut à toi !' },
  COUCOU:    { emoji: '👋', text: 'Coucou !' },
  MERCI:     { emoji: '🙏', text: 'De rien.' },
  BRAVO:     { emoji: '👏', text: 'Bien joué !' },
  GENIAL:    { emoji: '🎉', text: 'Effectivement.' },
  PARIS:     { emoji: '🗼', text: 'La plus belle.' },
  CHAT:      { emoji: '🐈', text: 'Miaou.' },
  CHIEN:     { emoji: '🐕', text: 'Wouaf !' },
  BOUM:      { emoji: '💥', text: 'Boum !' },
  PAN:       { emoji: '💥', text: 'Pan !' },
  LOL:       { emoji: '😂', text: 'mdr' },
  OUF:       { emoji: '😅', text: 'De justesse.' },
  WAOUH:     { emoji: '🤩', text: 'Impressionnant.' },
  CAFE:      { emoji: '☕', text: 'Un petit café ?' },
  BIERE:     { emoji: '🍺', text: 'Santé !' },
  VIN:       { emoji: '🍷', text: 'À votre santé.' },
  PIZZA:     { emoji: '🍕', text: 'Faim ?' },
  FROMAGE:   { emoji: '🧀', text: 'Classique.' },
  SOLEIL:    { emoji: '☀️', text: 'Rayonnant.' },
  LUNE:      { emoji: '🌙', text: 'Rêveuse.' },
  ETOILE:    { emoji: '⭐', text: '' },
  AMOUR:     { emoji: '💖', text: '' },
  BISOU:     { emoji: '😘', text: 'Mwah !' },
  FOU:       { emoji: '🤪', text: 'Complètement.' },
  BIDULE:    { emoji: '🔧', text: 'Un truc, quoi.' },
  ZUT:       { emoji: '🙄', text: 'Mince alors.' },
  HOP:       { emoji: '🏃', text: 'Hop hop hop !' },
  QI:        { emoji: '🧠', text: 'Astucieux.' },
  ZEN:       { emoji: '🧘', text: 'Respire.' },
  JAZZ:      { emoji: '🎷', text: '🎵' },
};

export const COACH_QUOTES: string[] = [
  "Un bon rack est un rack équilibré.",
  "Passer vaut parfois mieux que mal jouer.",
  "Les jokers valent leur poids en or.",
  "Visez les cases rouges quand vos lettres sont chères.",
  "Un scrabble = 50 points bonus. Ça se cherche.",
  "Les lettres chères sont surévaluées hors case premium.",
  "Toujours regarder les raccrocs avant de poser.",
  "Un bingo rapporte plus qu'un gros mot mal placé.",
  "Le S est précieux — pensez pluriels et conjugaisons.",
  "Le Q sans U : QI, QAT, COQ, CINQ.",
  "Vocalique ? Consonnes ? Rééquilibrez avec un petit mot.",
  "Les meilleures poses gênent l'adversaire (ou vous-même).",
  "Compter les lettres restantes = lire l'avenir.",
];
