// Words that trigger a little celebration toast when they land on the board
// (via the top move or the player's own move).
export const EASTER_EGGS: Record<string, { emoji: string; text: string }> = {
  SALUT:     { emoji: '👋', text: 'Salut à toi !' },
  COUCOU:    { emoji: '👋', text: 'Coucou !' },
  MERCI:     { emoji: '🙏', text: 'De rien.' },
  BRAVO:     { emoji: '👏', text: 'Bien joué !' },
  GENIAL:    { emoji: '🎉', text: 'Effectivement.' },
  PARIS:     { emoji: '🗼', text: 'La plus belle.' },
  CHAT:      { emoji: '🐈', text: 'Miaou.' },
  CHIEN:     { emoji: '🐕', text: 'Wouaf !' },
  BOUM:      { emoji: '💥', text: 'Boum !' },
  PAN:       { emoji: '💥', text: 'Pan !' },
  LOL:       { emoji: '😂', text: 'mdr' },
  OUF:       { emoji: '😅', text: 'De justesse.' },
  WAOUH:     { emoji: '🤩', text: 'Impressionnant.' },
  CAFE:      { emoji: '☕', text: 'Un petit café ?' },
  BIERE:     { emoji: '🍺', text: 'Santé !' },
  VIN:       { emoji: '🍷', text: 'À votre santé.' },
  PIZZA:     { emoji: '🍕', text: 'Faim ?' },
  FROMAGE:   { emoji: '🧀', text: 'Classique.' },
  SOLEIL:    { emoji: '☀️', text: 'Rayonnant.' },
  LUNE:      { emoji: '🌙', text: 'Rêveuse.' },
  ETOILE:    { emoji: '⭐', text: '' },
  AMOUR:     { emoji: '💖', text: '' },
  BISOU:     { emoji: '😘', text: 'Mwah !' },
  FOU:       { emoji: '🤪', text: 'Complètement.' },
  BIDULE:    { emoji: '🔧', text: 'Un truc, quoi.' },
  ZUT:       { emoji: '🙄', text: 'Mince alors.' },
  HOP:       { emoji: '🏃', text: 'Hop hop hop !' },
  QI:        { emoji: '🧠', text: 'Astucieux.' },
  ZEN:       { emoji: '🧘', text: 'Respire.' },
  JAZZ:      { emoji: '🎷', text: '🎵' },
};

// Cheap out-of-context "advice" served up by the fake hint panel.
// None of these help you play Scrabble. That's the point.
export const RANDOM_THOUGHTS: string[] = [
  "Et si la moutarde était secrètement vivante ?",
  "Tu as bien éteint le four ce matin ? Vérifie quand même.",
  "Les pigeons ont-ils des sourcils ? Personne ne le sait.",
  "Bois un verre d'eau. Là, maintenant.",
  "Ton chat te juge. Discrètement, mais sévèrement.",
  "Pose une lettre. N'importe laquelle. Au pif.",
  "J'avais un super conseil. Je l'ai oublié en chemin.",
  "Et si tu prenais une douche à la place ?",
  "Dans une autre vie, tu aurais été potier en Crète.",
  "Le mot \"haricot\" est plus drôle que \"légume\". Statistiquement.",
  "Ferme les yeux. Respire. Recommence.",
  "Avez-vous nourri votre plante aujourd'hui ?",
  "Quelque part, un escargot fait la course. Et il gagne.",
  "Le secret, c'est de croire en soi. (Mais pas trop.)",
  "Je connaissais le meilleur coup. Mais je pensais à des frites.",
  "Et si on commandait des sushis ?",
  "L'univers se moque de ton score, et c'est libérateur.",
  "Tu as un cheveu qui dépasse, à droite.",
  "As-tu déjà essayé de chuchoter à une fourmi ?",
  "Quand le sage montre la lune, l'idiot regarde le rack.",
  "Pose ce que tu veux, je m'en occupe. Tranquille.",
  "Le 7 est un chiffre suspect. Pourquoi ? Personne ne sait.",
  "Si tu lis ceci, tu es probablement humain. Probablement.",
  "Demande-toi : qu'aurait fait Lagarde ?",
  "Tu peux jouer un mot. Ou rien. C'est toi qui vois.",
  "Le pain au chocolat est meilleur tiède.",
  "Quelque part, un pigeon vient de gagner aux échecs.",
  "Pense à ta posture. Redresse-toi.",
  "Et si on partait en Corse à la place ?",
  "Le tirage parfait n'existe pas. Le pain perdu, oui.",
  "Tu as oublié quelque chose. Mais quoi ?",
  "Les meilleures idées arrivent sous la douche.",
  "Mots croisés ou Scrabble ? Le débat fait rage.",
  "Un proverbe inventé est toujours plus profond.",
  "Range ta cuisine après. Promis ?",
  "Les chaussettes orphelines vont au paradis.",
  "Si tu doutes, ajoute un \"S\".",
  "L'inspiration vient en marchant. Lève-toi.",
  "C'est mathématique : un câlin = 7 points de bonheur.",
  "Pose un mot, n'importe lequel. Vraiment.",
  "Aujourd'hui, le hasard est ton ami. Demain, on verra.",
  "Sache que je crois en toi. Modérément.",
  "L'ennui est l'antichambre de la créativité. Apparemment.",
  "Tu joues bien. Enfin, je suppose.",
];

export const COACH_QUOTES: string[] = [
  "Un bon rack est un rack équilibré.",
  "Passer vaut parfois mieux que mal jouer.",
  "Les jokers valent leur poids en or.",
  "Visez les cases rouges quand vos lettres sont chères.",
  "Un scrabble = 50 points bonus. Ça se cherche.",
  "Les lettres chères sont surévaluées hors case premium.",
  "Toujours regarder les raccrocs avant de poser.",
  "Un bingo rapporte plus qu'un gros mot mal placé.",
  "Le S est précieux — pensez pluriels et conjugaisons.",
  "Le Q sans U : QI, QAT, COQ, CINQ.",
  "Vocalique ? Consonnes ? Rééquilibrez avec un petit mot.",
  "Les meilleures poses gênent l'adversaire (ou vous-même).",
  "Compter les lettres restantes = lire l'avenir.",
];
